<a href="https://colab.research.google.com/github/elakiya04/machine-learning-basics/blob/main/MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MNIST DATASET BINARY CLASSIFICATION

In [14]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, confusion_matrix

## TEST TRAIN SPLIT

In [2]:
X=pd.DataFrame(load_digits().data, 
                       columns=load_digits().feature_names)

y = pd.DataFrame(load_digits().target)

In [6]:
x.shape, y.shape

((1797, 64), (1797,))

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

## LINEAR REGRESSION

In [15]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(multi_class="multinomial", random_state=42)
logistic_classifier = logistic_model.fit(X_train, y_train)

y_pred_logistic = logistic_model.predict(X_test)
MAE=mean_absolute_error(Y_test, y_pred)
MSE=mean_squared_error(Y_test, y_pred)
RMSE=np.sqrt(MSE)
r2=r2_score(Y_test, y_pred)
conmat=confusion_matrix(y_test, y_pred_sgd)
print("Mean Absolute Error=", MAE)
print("Mean Squared Error=", MSE)
print("Root Mean Squared Error=", RMSE)
print("R2 score=", r2)
print("CONFUSION MATRIX")
print(conmat)

Mean Absolute Error= 0.2733333333333333
Mean Squared Error= 1.5133333333333334
Root Mean Squared Error= 1.230176139149729
R2 score= 0.8115291630098999
CONFUSION MATRIX
[[ 7  3 15  2 14  2  1  4  6  0]
 [ 5  5 13  1  8  4  7  5  5  0]
 [11  3 11  0  5  2  4  1  3  1]
 [10  5 11  1  4  1  4  4  4  2]
 [ 6  2 10  2  9  4  5  2  3  0]
 [ 9  3  8  2  4  3  6  5  6  0]
 [ 7  5  5  2  6  3  3  3  5  1]
 [ 8  0  5  2  6  4  5  1  5  1]
 [11  1  8  5  4  1  1  6  4  1]
 [ 5  6  8  4 13  1  1  4  5  1]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


## SGD CLASSIFIER

In [16]:
model2=SGDClassifier()
model2.fit(X_train, Y_train)
y_pred=model2.predict(X_test)
MAE=mean_absolute_error(Y_test, y_pred)
MSE=mean_squared_error(Y_test, y_pred)
RMSE=np.sqrt(MSE)
r2=r2_score(Y_test, y_pred)
conmat=confusion_matrix(y_test, y_pred_sgd)
print("Mean Absolute Error=", MAE)
print("Mean Squared Error=", MSE)
print("Root Mean Squared Error=", RMSE)
print("R2 score=", r2)
print("CONFUSION MATRIX")
print(conmat)

Mean Absolute Error= 0.28
Mean Squared Error= 1.528888888888889
Root Mean Squared Error= 1.2364824660660938
R2 score= 0.8095918709997226
CONFUSION MATRIX
[[ 7  3 15  2 14  2  1  4  6  0]
 [ 5  5 13  1  8  4  7  5  5  0]
 [11  3 11  0  5  2  4  1  3  1]
 [10  5 11  1  4  1  4  4  4  2]
 [ 6  2 10  2  9  4  5  2  3  0]
 [ 9  3  8  2  4  3  6  5  6  0]
 [ 7  5  5  2  6  3  3  3  5  1]
 [ 8  0  5  2  6  4  5  1  5  1]
 [11  1  8  5  4  1  1  6  4  1]
 [ 5  6  8  4 13  1  1  4  5  1]]
